version: "3.9"
services:
  front:
    container_name: front
    build: ./front
    ports:
      - "3000:3000"
    links:
      - back
  back:
    container_name: back
    build: ./back
    ports:
      - "5000:5000"
