version: "3.9"
services:
  front:
    container_name: front
    build: ./front
    ports:
      - "3000:3000"
    links:
      - back
    volumes:
      - ./front/src:/front/src
  back:
    container_name: back
    build: ./back
    volumes:
      - ./back:/back
    ports:
      - "5000:5000"
